parameters = [
  { name = "dev.frontend.catalog_url" , value = "http://catalogue.jkdevops.online:8080/"},
  { name = "dev.frontend.cart_url" , value = "http://cart.jkdevops.online:8080/"},
  { name = "dev.frontend.user_url" , value = "http://user.jkdevops.online:8080/"},
  { name = "dev.frontend.shipping_url" , value = "http://shipping.jkdevops.online:8080/"},
  { name = "dev.frontend.payment_url" , value = "http://payment.jkdevops.online:8080/"},
  { name = "dev.catalogue.mongo_endpoint" , value = "mongodb.jkdevops.online"},
  { name = "dev.catalogue.mongo" , value = "MONGO=true"},
  { name = "dev.catalogue.mongo_url" , value = "mongodb://mongodb.jkdevops.online:27017/catalogue"},
  { name = "dev.user.mongo" , value = "MONGO=true"},
  { name = "dev.user.redis_host" , value = "redis.jkdevops.online"},
  { name = "dev.user.mongo_url" , value = "mongodb://mongodb.jkdevops.online:27017/users"},
  { name = "dev.cart.redis_host" , value = "redis.jkdevops.online"},
  { name = "dev.cart.catalogue_host" , value = "catalogue.jkdevops.online"},
  { name = "dev.cart.catalogue_port" , value = "8080"},
  { name = "dev.shipping.cart_endpoint" , value = "cart.jkdevops.online:8080"},
  { name = "dev.shipping.db_host" , value = "mysql.jkdevops.online"},
  { name = "dev.shipping.mysql_url" , value = "mysql.jkdevops.online"},
  { name = "dev.shipping.db_user" , value = "root"},
  { name = "dev.shipping.db_pass" , value = "RoboShop@1"},
  { name = "dev.payment.cart_host" , value = "cart.jkdevops.online"},
  { name = "dev.payment.cart_port" , value = "8080"},
  { name = "dev.payment.user_host" , value = "user.jkdevops.online"},
  { name = "dev.payment.user_port" , value = "8080"},
  { name = "dev.payment.amqp_host" , value = "rabbitmq.jkdevops.online"},
  { name = "dev.payment.amqp_user" , value = "roboshop"},
  { name = "dev.payment.amqp_pass" , value = "roboshop123"},
  { name = "dev.dispatch.amqp_host" , value = "rabbitmq.jkdevops.online"},
  { name = "dev.dispatch.amqp_user" , value = "roboshop"},
  { name = "dev.dispatch.amqp_pass" , value = "roboshop123"}

]
